project_id = "fsrelhcbfrpfprmzkjmo"

[functions.analyze-essay]
verify_jwt = true

[functions.track-essay-analytics]
verify_jwt = true

[functions.export-analytics]
verify_jwt = true

[functions.parse-portfolio-essay]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.send-user-emails]
verify_jwt = true

[functions.export-essay-docx]
verify_jwt = true

[functions.create-training-snapshot]
verify_jwt = true